apiVersion: v1
kind: Namespace
metadata:
  name: argo-apache-deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  namespace: argo-apache-deployment
spec:
  replicas: 1  # Pode ser ajustado conforme necessário
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: httpd:latest  # Imagem do Apache
        ports:
        - containerPort: 80   # Porta do Apache
---
apiVersion: v1
kind: Service
metadata:
  name: apache-service
  namespace: argo-apache-deployment
spec:
  type: LoadBalancer  # Pode ser alterado para ClusterIP se necessário
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: apache
