apiVersion: v1
kind: Namespace
metadata:
  name: argo-apache-deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  namespace: argo-apache-deployment
spec:
  replicas: 1  # Ajuste conforme necessário
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: httpd:latest  # Imagem do Apache
        ports:
        - containerPort: 80   # Porta do Apache
---
apiVersion: v1
kind: Service
metadata:
  name: apache-service
  namespace: argo-apache-deployment
spec:
  selector:
    app: apache
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer  # LoadBalancer para exposição pública
---
apiVersion: v1
kind: Service
metadata:
  name: apache-nodeport-service
  namespace: argo-apache-deployment
spec:
  type: NodePort  # Tipo NodePort para acesso nos nós do cluster
  ports:
    - port: 80        # Porta exposta
      targetPort: 80  # Porta dentro do container
      protocol: TCP
      nodePort: 30080 # Porta específica no nó (ajustável)
  selector:
    app: apache
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apache-ingress
  namespace: argo-apache-deployment
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: apache.example.com  # Substitua pelo seu domínio ou IP
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: apache-service  # Nome do serviço LoadBalancer
            port:
              number: 80
