apiVersion: v1
kind: Namespace
metadata:
  name: argo-ubuntu-python-node-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-python-node
  namespace: argo-ubuntu-python-node-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-python-node
  template:
    metadata:
      labels:
        app: ubuntu-python-node
    spec:
      containers:
        - name: ubuntu-container
          image: ubuntu:22.04
          command: ["/bin/bash", "-c"]
          args:
            - |
              apt-get update && apt-get upgrade -y &&
              apt-get install -y net-tools htop iftop nano openssh-server python3-pip &&
              pip3 install flask subprocess &&
              service ssh start &&
              echo "root:admin" | chpasswd &&
              echo "admin:admin" | chpasswd &&
              service ssh restart &&
              /usr/sbin/sshd -D
          ports:
            - containerPort: 22
            - containerPort: 7777
          securityContext:
            privileged: true
---
apiVersion: v1
kind: Service
metadata:
  name: ubuntu-python-node-service
  namespace: argo-ubuntu-python-node-dev
spec:
  type: NodePort
  ports:
    - name: ssh
      port: 22
      targetPort: 22
      nodePort: 30022  # Porta NodePort para SSH
    - name: app-port
      port: 7777
      targetPort: 7777
      nodePort: 30777  # Porta NodePort para o aplicativo
  selector:
    app: ubuntu-python-node
